class DashComponentID:
    DATE_PICKER = "date-picker-select"
    RUN_BTN = "btn-run"
    STOCK_DROP_DOWN = "stock-dropdown"
    PRICE_CHART = "price-chart"
    PRICE_TABLE = "price-table"
    VOLUME_CHART = "volume-chart"
    VOLUME_TABLE = "volume-table"
    CUM_RETURN_CHART = "cum-return-chart"
    SECTOR_PIE_CHART = "sector-pie-chart"
    CUM_RETURN_TABLE = "cum-return-table"
    SECTOR_TABLE = "sector-table"
    DOWNLOAD_DATA_BTN = "btn-download-data"
    ALL_CHARTS = "all-charts"
    PRICE_TABLE_DOWNLOAD_BUTTON = "price-table-download-button"
    VOLUME_TABLE_DOWNLOAD_BUTTON = "volume-table-download-button"
